export type AppPage =
  | 'home'
  | 'login'
  | 'register'
  | 'verification'
  | 'onboarding-user'
  | 'onboarding-vendor'
  | 'onboarding-partner'
  | 'pending'
  | 'pending-approval'
  | 'user-dashboard'
  | 'user-menu-order'
  | 'user-meal-recommendations'
  | 'user-wellness'
  | 'user-settings'
  | 'vendor-dashboard'
  | 'partner-dashboard';
